on: [push]

jobs:
  security_tests:
    runs-on: ubuntu-latest

    permissions:
      security-events: read

    steps:
    - uses: actions/checkout@v4
    - name: Build web image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/vulnerable-app:${{ github.sha }} \
          ./vulnerable-app

    - name: Start Vulnerable App
      run: |
        docker run -d --rm --name vulnapp \
          -p 8080:8080 \
          ghcr.io/${{ github.repository_owner }}/vulnerable-app:${{ github.sha }}

    - name: Wait Until Deployment...
      run: |
        for i in {1..30}; do
          curl -sSf http://localhost:8080 >/dev/null && break
          sleep 2
        done

    - name: Run DAST
      uses: zaproxy/action-full-scan@v0.12.0 
      with:
        target: 'http://localhost:8080/'
        fail_action: false 
        cmd_options: '-a'
        allow_issue_writing: 'false'
        docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
        
    - name: Stop Docker Container
      if: always()   
      run: docker stop web
